spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      host: localhost
      port: 27017
      database: botc
      username:
      password:
      authentication-database: admin

discord:
  token: ${DISCORD_TOKEN}
